# Generated by Django 5.1.4 on 2024-12-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
