# Generated by Django 5.1.4 on 2024-12-26 11:06

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to=management.models.upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(upload_to=management.models.upload_path),
        ),
    ]
